### ISSUE TITLE
Feature Request: automatic framing of loaded graphs

### ISSUE THREAD

**Issue by hybridherbst** [KhronosGroup/glTF-InteractivityGraph-AuthoringTool#11]
Not all tools produce the "metadata" property for where nodes are. I can see there's some auto-layouting going on, however, the view is not fitted to the loaded nodes after loading:

![20240813-134326_chrome-3455](https://github.com/user-attachments/assets/6d1bf1a9-0049-4ecb-aa6a-927d30f5c68c)

To reproduce, replace all occurences of "metadata" in exported JSONs with "_metadata".

**Comment by mattmacf98** [comment]
https://github.com/user-attachments/assets/6c124b57-0b9c-4f73-abe8-2f0878f2533d

Good Idea! just added auto-framing on load
