### ISSUE TITLE
onTick is missing output value sockets

### ISSUE THREAD

**Issue by boguscoder** [KhronosGroup/glTF-InteractivityGraph-AuthoringTool#18]
Apologies if you are not accepting issues for work-in-progress branch

`event/onTick` node seems bare and is missing both `float timeSinceStart` and `float timeSinceLastTick` output value sockets. Adding them would allow for a lot better feedback mechanism/tests

**Comment by mattmacf98** [comment]
https://github.com/user-attachments/assets/ad39dbd5-4f5f-456a-80f3-36a53f03921c

ah those were a later addition to the spec, just added them in
