### ISSUE TITLE
`math/extract` nodes are missing

### ISSUE THREAD

**Issue by hybridherbst** [KhronosGroup/glTF-InteractivityGraph-AuthoringTool#19]
I think the extract nodes are currently missing:
https://github.com/KhronosGroup/glTF/blob/interactivity/extensions/2.0/Khronos/KHR_interactivity/Specification.adoc#36189-extract

As counterparts of `math/combine` they're quite useful.

**Comment by mattmacf98** [comment]
ah yeah I have them implemented just forgot to include them in the authoringNodeSpecs export 🤦

**Comment by mattmacf98** [comment]
![Screenshot 2024-08-29 at 1 46 43 PM](https://github.com/user-attachments/assets/a522923c-6dcf-41e2-bc9e-53675e2250d5)
 they are available now

**Comment by hybridherbst** [comment]
Haha, thanks!
