### ISSUE TITLE
Incorrect JSON export with duplicate output entries for the same id

### ISSUE THREAD

**Issue by hybridherbst** [KhronosGroup/glTF-InteractivityGraph-AuthoringTool#20]
I believe this is invalid JSON, as the "values" entry contains multiple identical IDs for the math/sign nodes.

To reproduce,
1. create "math/extract2"
2. create "math/sign"
3. create another "math/sign"
4. connect both sign nodes to the extract2 node
5. Expected: types automatically switch to "float"
6. Actual: types stay at "int"
7. manually switch to "float"
8. Click on "JSON view"
9. Note that the sign nodes are exported with multiple entries for id: "a" which I believe is not allowed.

<img width="520" alt="image" src="https://github.com/user-attachments/assets/d6bd004c-dac2-4099-82b9-ac21327c5102">

```json
{
	"nodes": [
		{
			"type": "math/extract2",
			"values": [],
			"configuration": [],
			"flows": [],
			"metadata": {
				"positionX": "75.34715001777437",
				"positionY": "145.9530971058138"
			}
		},
		{
			"type": "math/sign",
			"values": [
				{
					"id": "a",
					"value": [
						null
					],
					"type": 2
				},
				{
					"id": "a",
					"node": 0,
					"socket": "0"
				}
			],
			"configuration": [],
			"flows": [],
			"metadata": {
				"positionX": "529.6785585536945",
				"positionY": "119.12613798828914"
			}
		},
		{
			"type": "math/sign",
			"values": [
				{
					"id": "a",
					"value": [
						null
					],
					"type": 2
				},
				{
					"id": "a",
					"node": 0,
					"socket": "1"
				}
			],
			"configuration": [],
			"flows": [],
			"metadata": {
				"positionX": "464.87505088326293",
				"positionY": "327.71242830249076"
			}
		}
	],
	"variables": [],
	"customEvents": [],
	"types": [
		{
			"signature": "bool"
		},
		{
			"signature": "int"
		},
		{
			"signature": "float"
		},
		{
			"signature": "float2"
		},
		{
			"signature": "float3"
		},
		{
			"signature": "float4"
		},
		{
			"signature": "float4x4"
		},
		{
			"signature": "custom",
			"extensions": {
				"AMZN_interactivity_string": {}
			}
		}
	]
}
```

To reproduce:

**Comment by mattmacf98** [comment]
https://github.com/user-attachments/assets/f5f9bdc8-1b6b-4efe-9465-8c9fca777b74

yes that is correct, the root cause of the issue was that connecting a input value did not wipe the inlined one, I have fixed that bug

**Comment by hybridherbst** [comment]
Should it wipe it or rather just overwrite it on export? When connecting and then deconnecting a port, the old value should probably be back instead of being reset
