### ISSUE TITLE
Bug:variable/get does not connect to pointer/set.

### ISSUE THREAD

**Issue by Hackn0214** [KhronosGroup/glTF-InteractivityGraph-AuthoringTool#24]
Uploade a glb file with the out-socket of variable/get node is connected to the variable of pointer/set node,
the nodes were loaded, but the connection between them was broken.
[MyTest.glb.zip](https://github.com/user-attachments/files/17006178/MyTest.glb.zip)
![gltftest](https://github.com/user-attachments/assets/58ac9cd2-229f-4677-8d20-194eea1c1938)

**Comment by mattmacf98** [comment]
https://github.com/user-attachments/assets/b45b1003-a603-4487-baef-0215f9e22e09

There was an issue with the dropdown not picking up the selected config from the graph (I just fixed that see video)

I also saw in your variable get node looks like this

```
{"configuration":[{"id":"variable","type":1,"value":0}],"type":"variable/get"}
```

but the spec says single valued items should be singleton arrays https://github.com/KhronosGroup/glTF/blob/interactivity/extensions/2.0/Khronos/KHR_interactivity/Specification.adoc#:~:text=variable%22%2C-,%22value%22%3A%20%5B0%5D,-%7D%0A%20%20%20%20%5D%2C%0A%20%20%20%20%22values%22

so it should be

```
{"configuration":[{"id":"variable","type":1,"value":[0]}],"type":"variable/get"}
```

**Comment by Hackn0214** [comment]
Thank you for the support with the Variable ID issue.
I also appreciate you pointing out the issues on my side.
If possible, could you change the name of the value input socket for each node from "val" to "value" to match the spec?

**Comment by mattmacf98** [comment]
This specific socket naming instance is fixed now thanks to @hybridherbst! I plan to fix the rest of the names later as part of https://github.com/KhronosGroup/glTF-InteractivityGraph-AuthoringTool/issues/27
