### ISSUE TITLE
pointer/get node doesn't accept read only runtime property

### ISSUE THREAD

**Issue by maxmaynard** [KhronosGroup/glTF-InteractivityGraph-AuthoringTool#33]
I'm trying to use a flow/for node to apply the same transform to each mesh in a gltf; according the gltf 2.0 specifications on Object models, there should be a pointer template for /nodes.length and /meshes.length, but when I enter those strings into a pointer/get node I get a type error  when I trigger the graph.
![image](https://github.com/user-attachments/assets/ed9ac9e0-98a3-46f3-b0f9-28342ee7a703)
![image](https://github.com/user-attachments/assets/5c0035d3-e321-486b-8a32-bc9dff7baf48)
![image](https://github.com/user-attachments/assets/1115d8c3-5fa8-4ca8-9046-2402952ec073)

**Comment by mattmacf98** [comment]
Yes, I have not implemented those read only pointers yet, I’ll see if I can get to it this week

**Comment by mattmacf98** [comment]
https://github.com/user-attachments/assets/6cae364a-c397-4e61-b668-1d169060b30a

Just added support for the node.length read only path and a couple others

**Comment by maxmaynard** [comment]
Awesome, thank you!
