### ISSUE TITLE
Show Variables window can be cut off by graph window

### ISSUE THREAD

**Issue by maxmaynard** [KhronosGroup/glTF-InteractivityGraph-AuthoringTool#37]
If you have more than a certain number of variables in a gltf, clicking the "Show Variables" button brings up the window, but you can't see the variables at the bottom of the UI.

![image](https://github.com/user-attachments/assets/1e6d2c16-a486-44c3-9e17-fcf9883295ed)

**Comment by mattmacf98** [comment]
https://github.com/user-attachments/assets/3d685853-1c15-4431-af3f-e6d11f73ca78

I have made the variables window and the custom events window scrollable now
